<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviceConfig [
	<!ELEMENT serviceConfig (IDlabelMapping, favoritesGermany, favoritesAustria, TVlistWithGenreSatellite, (TVlistWithGenreCableSpecific)+, TVlistWithGenreCableGeneral, TVlistWithoutGenre, radioList, DRM)>
	<!ELEMENT IDlabelMapping (mapping)+>
	<!ELEMENT mapping (genreID, genreLabel)>
	<!ELEMENT genreID (#PCDATA)>
	<!ELEMENT genreLabel (#PCDATA)>
	<!ELEMENT favoritesGermany (svc)+>
	<!ELEMENT svc (TSID, SID, ONID, svcNum)>
	<!ELEMENT TSID (#PCDATA)>
	<!ELEMENT SID (#PCDATA)>
	<!ELEMENT ONID (#PCDATA)>
	<!ELEMENT svcNum (#PCDATA)>
	<!ELEMENT favoritesAustria (svc)+>
	<!ELEMENT TVlistWithGenreSatellite (versionNumber, referenceServiceNumber, selectServiceNumber, (svcWithGenre)+)>
	<!ELEMENT versionNumber (#PCDATA)>
	<!ELEMENT referenceServiceNumber (#PCDATA)>
	<!ELEMENT selectServiceNumber (#PCDATA)>
	<!ELEMENT svcWithGenre (TSID, SID, ONID, svcNum, genreID*)>
	<!ELEMENT TVlistWithGenreCableSpecific (versionNumber, (NID)+, referenceServiceNumber, selectServiceNumber, (svcWithGenre)+)>
	<!ELEMENT NID (#PCDATA)>
	<!ELEMENT TVlistWithGenreCableGeneral (versionNumber, referenceServiceNumber, selectServiceNumber, (svcWithGenre)+)>
	<!ELEMENT TVlistWithoutGenre (versionNumber, referenceServiceNumber, selectServiceNumber, (svc)+)>
	<!ELEMENT radioList (svc)*>
	<!ELEMENT DRM (DRMsvc)*>
	<!ELEMENT DRMsvc (TSID, SID, ONID, TIMESHIFT, REC)>
	<!ELEMENT TIMESHIFT (#PCDATA)>
	<!ELEMENT REC (#PCDATA)>
]>
<serviceConfig>
	<IDlabelMapping>
		<mapping>
			<genreID>0</genreID>
			<genreLabel>HD-Sender</genreLabel>
		</mapping>
		<mapping>
			<genreID>10</genreID>
			<genreLabel>Sky Sender</genreLabel>
		</mapping>
		<mapping>
			<genreID>1</genreID>
			<genreLabel>Unterhaltung &amp; Serie</genreLabel>
		</mapping>
		<mapping>
			<genreID>2</genreID>
			<genreLabel>Sport</genreLabel>
		</mapping>
		<mapping>
			<genreID>3</genreID>
			<genreLabel>Film</genreLabel>
		</mapping>
		<mapping>
			<genreID>4</genreID>
			<genreLabel>Doku</genreLabel>
		</mapping>
		<mapping>
			<genreID>5</genreID>
			<genreLabel>Kinder</genreLabel>
		</mapping>
		<mapping>
			<genreID>6</genreID>
			<genreLabel>Musik</genreLabel>
		</mapping>
		<mapping>
			<genreID>7</genreID>
			<genreLabel>News &amp; International</genreLabel>
		</mapping>
		<mapping>
			<genreID>8</genreID>
			<genreLabel>Regionales</genreLabel>
		</mapping>
		<mapping>
			<genreID>9</genreID>
			<genreLabel>Marktplatz</genreLabel>
		</mapping>
	</IDlabelMapping>

	<favoritesGermany>
	<svc><!-- Das Erste HD - Satellit --><TSID>3FB</TSID><SID>283D</SID><ONID>1</ONID><svcNum>1</svcNum></svc>
	<svc><!-- Das Erste HD - Kabel BW --><TSID>41B</TSID><SID>2B5C</SID><ONID>A401</ONID><svcNum>1</svcNum></svc>
	<svc><!-- Das Erste HD - Kabeldeutschland --><TSID>41B</TSID><SID>2B5C</SID><ONID>1</ONID><svcNum>1</svcNum></svc>
	<svc><!-- ZDF HD - Satellit --><TSID>3F3</TSID><SID>2B66</SID><ONID>1</ONID><svcNum>2</svcNum></svc>
	<svc><!-- ZDF HD - Kabel BW --><TSID>437</TSID><SID>2B66</SID><ONID>66</ONID><svcNum>2</svcNum></svc>
	<svc><!-- ZDF HD - Kabeldeutschland --><TSID>437</TSID><SID>2B66</SID><ONID>1</ONID><svcNum>2</svcNum></svc>
	<svc><!-- RTL Television - Satellit --><TSID>441</TSID><SID>2EE3</SID><ONID>1</ONID><svcNum>3</svcNum></svc>
	<svc><!-- RTL Television - Kabel BW --><TSID>A1</TSID><SID>2F45</SID><ONID>270F</ONID><svcNum>3</svcNum></svc>
	<svc><!-- RTL Television - Kabeldeutschland --><TSID>2710</TSID><SID>D161</SID><ONID>F001</ONID><svcNum>3</svcNum></svc>
	<svc><!-- SAT.1 - Satellit --><TSID>453</TSID><SID>445C</SID><ONID>1</ONID><svcNum>4</svcNum></svc>
	<svc><!-- SAT.1 - Kabel BW --><TSID>A1</TSID><SID>2F46</SID><ONID>270F</ONID><svcNum>4</svcNum></svc>
	<svc><!-- SAT.1 - Kabeldeutschland --><TSID>2710</TSID><SID>D17A</SID><ONID>F001</ONID><svcNum>4</svcNum></svc>
	<svc><!-- VOX - Satellit --><TSID>441</TSID><SID>2F1C</SID><ONID>1</ONID><svcNum>5</svcNum></svc>
	<svc><!-- VOX - Kabel BW --><TSID>A1</TSID><SID>2F48</SID><ONID>270F</ONID><svcNum>5</svcNum></svc>
	<svc><!-- VOX - Kabeldeutschland --><TSID>2713</TSID><SID>D164</SID><ONID>F001</ONID><svcNum>5</svcNum></svc>
	<svc><!-- ProSieben - Satellit --><TSID>453</TSID><SID>445D</SID><ONID>1</ONID><svcNum>6</svcNum></svc>
	<svc><!-- ProSieben - Kabel BW --><TSID>A1</TSID><SID>2F47</SID><ONID>270F</ONID><svcNum>6</svcNum></svc>
	<svc><!-- ProSieben - Kabeldeutschland --><TSID>2718</TSID><SID>D175</SID><ONID>F001</ONID><svcNum>6</svcNum></svc>
	<svc><!-- kabel eins - Satellit --><TSID>453</TSID><SID>445E</SID><ONID>1</ONID><svcNum>7</svcNum></svc>
	<svc><!-- kabel eins - Kabel BW --><TSID>A1</TSID><SID>2F4A</SID><ONID>270F</ONID><svcNum>7</svcNum></svc>
	<svc><!-- kabel eins - Kabeldeutschland --><TSID>2718</TSID><SID>D176</SID><ONID>F001</ONID><svcNum>7</svcNum></svc>
	<svc><!-- RTL2 - Satellit --><TSID>441</TSID><SID>2EF4</SID><ONID>1</ONID><svcNum>8</svcNum></svc>
	<svc><!-- RTL2 - Kabel BW --><TSID>A1</TSID><SID>2F49</SID><ONID>270F</ONID><svcNum>8</svcNum></svc>
	<svc><!-- RTL2 - Kabeldeutschland --><TSID>2713</TSID><SID>D163</SID><ONID>F001</ONID><svcNum>8</svcNum></svc>
	<svc><!-- zdf_neo HD - Satellit --><TSID>3F3</TSID><SID>2B7A</SID><ONID>1</ONID><svcNum>9</svcNum></svc>
	<svc><!-- zdf_neo HD - Kabel BW --><TSID>191</TSID><SID>A08F</SID><ONID>270F</ONID><svcNum>9</svcNum></svc>
	<svc><!-- zdf_neo HD - Kabeldeutschland --><TSID>2719</TSID><SID>2B7A</SID><ONID>F001</ONID><svcNum>9</svcNum></svc>
	<svc><!-- WDR HD Köln - Satellit --><TSID>4B1</TSID><SID>6EA5</SID><ONID>1</ONID><svcNum>10</svcNum></svc>
	<svc><!-- WDR HD Köln - Kabel BW --><TSID>6F</TSID><SID>2B93</SID><ONID>270F</ONID><svcNum>10</svcNum></svc>
	<svc><!-- WDR HD Köln - Kabeldeutschland --><TSID>41B</TSID><SID>6EA5</SID><ONID>1</ONID><svcNum>10</svcNum></svc>
	<svc><!-- BR Fernsehen Süd HD - Satellit --><TSID>401</TSID><SID>2855</SID><ONID>1</ONID><svcNum>11</svcNum></svc>
	<svc><!-- BR Fernsehen Süd HD - Kabel BW --><TSID>227</TSID><SID>D743</SID><ONID>270F</ONID><svcNum>11</svcNum></svc>
	<svc><!-- BR Fernsehen Süd HD - Kabeldeutschland --><TSID>44D</TSID><SID>2855</SID><ONID>1</ONID><svcNum>11</svcNum></svc>
	<svc><!-- SUPER RTL - Satellit --><TSID>441</TSID><SID>2F08</SID><ONID>1</ONID><svcNum>12</svcNum></svc>
	<svc><!-- SUPER RTL - Kabel BW --><TSID>A1</TSID><SID>2F4B</SID><ONID>270F</ONID><svcNum>12</svcNum></svc>
	<svc><!-- SUPER RTL - Kabeldeutschland --><TSID>2713</TSID><SID>D162</SID><ONID>F001</ONID><svcNum>12</svcNum></svc>
	<svc><!-- NITRO - Satellit --><TSID>441</TSID><SID>2F1D</SID><ONID>1</ONID><svcNum>13</svcNum></svc>
	<svc><!-- NITRO - Kabel BW --><TSID>B5</TSID><SID>75A2</SID><ONID>270F</ONID><svcNum>13</svcNum></svc>
	<svc><!-- NITRO - Kabeldeutschland --><TSID>2712</TSID><SID>CF76</SID><ONID>F001</ONID><svcNum>13</svcNum></svc>
	<svc><!-- NDR FS NDS HD - Satellit --><TSID>401</TSID><SID>2857</SID><ONID>1</ONID><svcNum>14</svcNum></svc>
	<svc><!-- NDR FS NDS HD - Kabeldeutschland --><TSID>431</TSID><SID>2857</SID><ONID>1</ONID><svcNum>14</svcNum></svc>
	<svc><!-- NDR FS NDS HD - Unity Media --><TSID>213</TSID><SID>CF73</SID><ONID>270F</ONID><svcNum>14</svcNum></svc>
	<svc><!-- SAT.1 Gold - Satellit --><TSID>453</TSID><SID>4460</SID><ONID>1</ONID><svcNum>15</svcNum></svc>
	<svc><!-- SAT.1 Gold - Kabel BW --><TSID>B5</TSID><SID>71B6</SID><ONID>270F</ONID><svcNum>15</svcNum></svc>
	<svc><!-- SAT.1 Gold - Kabeldeutschland --><TSID>2726</TSID><SID>D04C</SID><ONID>F001</ONID><svcNum>15</svcNum></svc>
	<svc><!-- 3sat HD - Satellit --><TSID>3F2</TSID><SID>2B8E</SID><ONID>1</ONID><svcNum>16</svcNum></svc>
	<svc><!-- 3sat HD - Kabel BW --><TSID>19B</TSID><SID>A08D</SID><ONID>270F</ONID><svcNum>16</svcNum></svc>
	<svc><!-- 3sat HD - Kabeldeutschland --><TSID>2721</TSID><SID>2B8E</SID><ONID>F001</ONID><svcNum>16</svcNum></svc>
	<svc><!-- MDR S-Anhalt HD - Satellit --><TSID>425</TSID><SID>2871</SID><ONID>1</ONID><svcNum>17</svcNum></svc>
	<svc><!-- MDR S-Anhalt - Kabel BW --><TSID>431</TSID><SID>6E45</SID><ONID>A401</ONID><svcNum>17</svcNum></svc>
	<svc><!-- MDR S-Anhalt HD - Kabeldeutschland --><TSID>431</TSID><SID>2871</SID><ONID>1</ONID><svcNum>17</svcNum></svc>
	<svc><!-- ZDFinfo HD - Satellit --><TSID>3F2</TSID><SID>2BA2</SID><ONID>1</ONID><svcNum>18</svcNum></svc>
	<svc><!-- ZDFinfo - Kabel BW --><TSID>437</TSID><SID>6D6B</SID><ONID>66</ONID><svcNum>18</svcNum></svc>
	<svc><!-- ZDFinfo - Kabeldeutschland --><TSID>437</TSID><SID>6D6B</SID><ONID>1</ONID><svcNum>18</svcNum></svc>
	<svc><!-- ZDFinfo HD - Kabeldeutschland --><TSID>437</TSID><SID>2BA2</SID><ONID>1</ONID><svcNum>18</svcNum></svc>
	<svc><!-- RTLplus - Satellit --><TSID>441</TSID><SID>2F30</SID><ONID>1</ONID><svcNum>19</svcNum></svc>
	<svc><!-- RTLplus - Kabeldeutschland --><TSID>2714</TSID><SID>D04F</SID><ONID>F001</ONID><svcNum>19</svcNum></svc>
	<svc><!-- arte HD - Satellit --><TSID>3FB</TSID><SID>283E</SID><ONID>1</ONID><svcNum>20</svcNum></svc>
	<svc><!-- arte HD - Kabel BW --><TSID>79</TSID><SID>42D9</SID><ONID>270F</ONID><svcNum>20</svcNum></svc>
	<svc><!-- arte HD - Kabeldeutschland --><TSID>271E</TSID><SID>2B70</SID><ONID>F001</ONID><svcNum>20</svcNum></svc>
	<svc><!-- n-tv - Satellit --><TSID>441</TSID><SID>2F3A</SID><ONID>1</ONID><svcNum>21</svcNum></svc>
	<svc><!-- n-tv - Kabel BW --><TSID>A1</TSID><SID>2F4D</SID><ONID>270F</ONID><svcNum>21</svcNum></svc>
	<svc><!-- n-tv - Kabeldeutschland --><TSID>2713</TSID><SID>D166</SID><ONID>F001</ONID><svcNum>21</svcNum></svc>
	<svc><!-- hr-fernsehen HD - Satellit --><TSID>425</TSID><SID>2873</SID><ONID>1</ONID><svcNum>22</svcNum></svc>
	<svc><!-- hr-fernsehen HD - Kabel BW --><TSID>231</TSID><SID>DB29</SID><ONID>270F</ONID><svcNum>22</svcNum></svc>
	<svc><!-- hr-fernsehen HD - Kabeldeutschland --><TSID>271E</TSID><SID>2873</SID><ONID>F001</ONID><svcNum>22</svcNum></svc>
	<svc><!-- PHOENIX HD - Satellit --><TSID>401</TSID><SID>285B</SID><ONID>1</ONID><svcNum>23</svcNum></svc>
	<svc><!-- PHOENIX HD - Kabel BW --><TSID>79</TSID><SID>2F53</SID><ONID>270F</ONID><svcNum>23</svcNum></svc>
	<svc><!-- PHOENIX HD - Kabeldeutschland --><TSID>2719</TSID><SID>285B</SID><ONID>F001</ONID><svcNum>23</svcNum></svc>
	<svc><!-- rbb Berlin HD - Satellit --><TSID>425</TSID><SID>286F</SID><ONID>1</ONID><svcNum>24</svcNum></svc>
	<svc><!-- rbb Berlin HD - Kabel BW --><TSID>245</TSID><SID>E2FA</SID><ONID>270F</ONID><svcNum>24</svcNum></svc>
	<svc><!-- rbb Berlin HD - Kabeldeutschland --><TSID>437</TSID><SID>286F</SID><ONID>1</ONID><svcNum>24</svcNum></svc>
	<svc><!-- KiKA HD - Satellit --><TSID>3F2</TSID><SID>2B98</SID><ONID>1</ONID><svcNum>25</svcNum></svc>
	<svc><!-- KiKA HD - Kabel BW --><TSID>6F</TSID><SID>2B91</SID><ONID>270F</ONID><svcNum>25</svcNum></svc>
	<svc><!-- KiKA HD - Kabeldeutschland --><TSID>2719</TSID><SID>2B98</SID><ONID>F001</ONID><svcNum>25</svcNum></svc>
	<svc><!-- DMAX - Satellit --><TSID>21</TSID><SID>3F</SID><ONID>85</ONID><svcNum>26</svcNum></svc>
	<svc><!-- DMAX - Kabel BW --><TSID>B5</TSID><SID>5E2C</SID><ONID>270F</ONID><svcNum>26</svcNum></svc>
	<svc><!-- DMAX - Kabeldeutschland --><TSID>2717</TSID><SID>D171</SID><ONID>F001</ONID><svcNum>26</svcNum></svc>
	<svc><!-- WELT - Satellit --><TSID>453</TSID><SID>445F</SID><ONID>1</ONID><svcNum>27</svcNum></svc>
	<svc><!-- WELT - Kabel BW --><TSID>BF</TSID><SID>2F4E</SID><ONID>270F</ONID><svcNum>27</svcNum></svc>
	<svc><!-- WELT - Kabeldeutschland --><TSID>2718</TSID><SID>D17B</SID><ONID>F001</ONID><svcNum>27</svcNum></svc>
	<svc><!-- SWR BW HD - Satellit --><TSID>3FB</TSID><SID>283F</SID><ONID>1</ONID><svcNum>28</svcNum></svc>
	<svc><!-- SWR BW HD - Kabel BW --><TSID>231</TSID><SID>DB2A</SID><ONID>270F</ONID><svcNum>28</svcNum></svc>
	<svc><!-- SWR BW HD - Kabeldeutschland --><TSID>431</TSID><SID>283F</SID><ONID>1</ONID><svcNum>28</svcNum></svc>
	<svc><!-- Disney Channel - Satellit --><TSID>5</TSID><SID>701</SID><ONID>85</ONID><svcNum>29</svcNum></svc>
	<svc><!-- Disney Channel - Kabel BW --><TSID>BF</TSID><SID>2B5E</SID><ONID>270F</ONID><svcNum>29</svcNum></svc>
	<svc><!-- Disney Channel - Kabeldeutschland --><TSID>2714</TSID><SID>C3B5</SID><ONID>F001</ONID><svcNum>29</svcNum></svc>
	<svc><!-- SPORT1 - Satellit --><TSID>21</TSID><SID>384</SID><ONID>85</ONID><svcNum>30</svcNum></svc>
	<svc><!-- SPORT1 - Kabel BW --><TSID>BF</TSID><SID>2F4C</SID><ONID>270F</ONID><svcNum>30</svcNum></svc>
	<svc><!-- SPORT1 - Kabeldeutschland --><TSID>2713</TSID><SID>D178</SID><ONID>F001</ONID><svcNum>30</svcNum></svc>
	<svc><!-- TELE 5 - Satellit --><TSID>21</TSID><SID>33</SID><ONID>85</ONID><svcNum>31</svcNum></svc>
	<svc><!-- TELE 5 - Kabel BW --><TSID>BF</TSID><SID>2F4F</SID><ONID>270F</ONID><svcNum>31</svcNum></svc>
	<svc><!-- TELE 5 - Kabeldeutschland --><TSID>2718</TSID><SID>CF0A</SID><ONID>F001</ONID><svcNum>31</svcNum></svc>
	<svc><!-- SIXX - Satellit --><TSID>5</TSID><SID>308</SID><ONID>85</ONID><svcNum>32</svcNum></svc>
	<svc><!-- SIXX - Kabel BW --><TSID>A1</TSID><SID>4E94</SID><ONID>270F</ONID><svcNum>32</svcNum></svc>
	<svc><!-- SIXX - Kabeldeutschland --><TSID>2718</TSID><SID>C60C</SID><ONID>F001</ONID><svcNum>32</svcNum></svc>
	<svc><!-- Pro7 MAXX - Satellit --><TSID>453</TSID><SID>4461</SID><ONID>1</ONID><svcNum>33</svcNum></svc>
	<svc><!-- Pro7 MAXX - Kabel BW --><TSID>A1</TSID><SID>2F51</SID><ONID>270F</ONID><svcNum>33</svcNum></svc>
	<svc><!-- Pro7 MAXX - Kabeldeutschland --><TSID>2721</TSID><SID>CF11</SID><ONID>F001</ONID><svcNum>33</svcNum></svc>
	<svc><!-- SWR RP HD - Satellit --><TSID>3FB</TSID><SID>2840</SID><ONID>1</ONID><svcNum>34</svcNum></svc>
	<svc><!-- SWR Fernsehen RP - Kabel BW --><TSID>431</TSID><SID>6E47</SID><ONID>A401</ONID><svcNum>34</svcNum></svc>
	<svc><!-- SWR RP HD - Kabeldeutschland --><TSID>41B</TSID><SID>2840</SID><ONID>1</ONID><svcNum>34</svcNum></svc>
	<svc><!-- ONE HD - Satellit --><TSID>40F</TSID><SID>2888</SID><ONID>1</ONID><svcNum>35</svcNum></svc>
	<svc><!-- ONE HD - Kabel BW --><TSID>1A5</TSID><SID>A08E</SID><ONID>270F</ONID><svcNum>35</svcNum></svc>
	<svc><!-- ONE HD - Kabeldeutschland --><TSID>2727</TSID><SID>2888</SID><ONID>F001</ONID><svcNum>35</svcNum></svc>
	<svc><!-- Eurosport 1 Deutschland - Satellit --><TSID>443</TSID><SID>79E0</SID><ONID>1</ONID><svcNum>36</svcNum></svc>
	<svc><!-- Eurosport 1 Deutschland - Kabel BW --><TSID>BF</TSID><SID>2B63</SID><ONID>270F</ONID><svcNum>36</svcNum></svc>
	<svc><!-- Eurosport 1 Deutschland - Kabeldeutschland --><TSID>2718</TSID><SID>D167</SID><ONID>F001</ONID><svcNum>36</svcNum></svc>
	<svc><!-- MDR Sachsen HD - Satellit --><TSID>425</TSID><SID>2870</SID><ONID>1</ONID><svcNum>37</svcNum></svc>
	<svc><!-- MDR Sachsen - Kabel BW --><TSID>431</TSID><SID>6E44</SID><ONID>A401</ONID><svcNum>37</svcNum></svc>
	<svc><!-- MDR Sachsen HD - Kabeldeutschland --><TSID>44D</TSID><SID>2870</SID><ONID>1</ONID><svcNum>37</svcNum></svc>
	<svc><!-- kabel eins Doku - Satellit --><TSID>453</TSID><SID>4465</SID><ONID>1</ONID><svcNum>38</svcNum></svc>
	<svc><!-- kabel eins Doku - Kabeldeutschland --><TSID>2725</TSID><SID>C3CA</SID><ONID>F001</ONID><svcNum>38</svcNum></svc>
	<svc><!-- TLC - Satellit --><TSID>5</TSID><SID>304</SID><ONID>85</ONID><svcNum>39</svcNum></svc>
	<svc><!-- TLC - Kabel BW --><TSID>C9</TSID><SID>69DF</SID><ONID>270F</ONID><svcNum>39</svcNum></svc>
	<svc><!-- TLC - Kabeldeutschland --><TSID>2712</TSID><SID>CFE4</SID><ONID>F001</ONID><svcNum>39</svcNum></svc>
	<svc><!-- tagesschau24 HD - Satellit --><TSID>40F</TSID><SID>2887</SID><ONID>1</ONID><svcNum>40</svcNum></svc>
	<svc><!-- tagesschau24 HD - Kabel BW --><TSID>023B</TSID><SID>DF0F</SID><ONID>270F</ONID><svcNum>40</svcNum></svc>
	<svc><!-- tagesschau24 HD - Kabeldeutschland --><TSID>2722</TSID><SID>C38E</SID><ONID>F001</ONID><svcNum>40</svcNum></svc>
	<svc><!-- ServusTV HD Deutschland - Satellit --><TSID>3EF</TSID><SID>1332</SID><ONID>1</ONID><svcNum>41</svcNum></svc>
	<svc><!-- ServusTV HD Deutschland - Kabel BW --><TSID>191</TSID><SID>71B5</SID><ONID>270F</ONID><svcNum>41</svcNum></svc>
	<svc><!-- ServusTV HD Deutschland - Kabeldeutschland --><TSID>2716</TSID><SID>C365</SID><ONID>F001</ONID><svcNum>41</svcNum></svc>
	<svc><!-- Radio Bremen TV - Satellit --><TSID>4B1</TSID><SID>6EE1</SID><ONID>1</ONID><svcNum>42</svcNum></svc>
	<svc><!-- Radio Bremen TV - Kabel BW --><TSID>1E1</TSID><SID>BBE8</SID><ONID>270F</ONID><svcNum>42</svcNum></svc>
	<svc><!-- Radio Bremen TV - Kabeldeutschland --><TSID>2710</TSID><SID>CB22</SID><ONID>F001</ONID><svcNum>42</svcNum></svc>
	<svc><!-- DELUXE MUSIC - Satellit --><TSID>7</TSID><SID>41</SID><ONID>85</ONID><svcNum>43</svcNum></svc>
	<svc><!-- DELUXE MUSIC - Kabel BW --><TSID>AB</TSID><SID>69DE</SID><ONID>270F</ONID><svcNum>43</svcNum></svc>
	<svc><!-- DELUXE MUSIC - Kabeldeutschland --><TSID>2726</TSID><SID>D04B</SID><ONID>F001</ONID><svcNum>43</svcNum></svc>
	<svc><!-- NDR FS HH HD - Satellit --><TSID>401</TSID><SID>2859</SID><ONID>1</ONID><svcNum>44</svcNum></svc>
	<svc><!-- NDR FS HH - Kabel BW --><TSID>431</TSID><SID>6E41</SID><ONID>A401</ONID><svcNum>44</svcNum></svc>
	<svc><!-- NDR FS HH HD - Kabeldeutschland --><TSID>44D</TSID><SID>2859</SID><ONID>1</ONID><svcNum>44</svcNum></svc>
	<svc><!-- rbb Brandenburg HD - Satellit --><TSID>425</TSID><SID>286E</SID><ONID>1</ONID><svcNum>45</svcNum></svc>
	<svc><!-- rbb Brandenburg - Kabel BW --><TSID>431</TSID><SID>6E2D</SID><ONID>A401</ONID><svcNum>45</svcNum></svc>
	<svc><!-- rbb Brandenburg HD - Kabeldeutschland --><TSID>431</TSID><SID>286E</SID><ONID>1</ONID><svcNum>45</svcNum></svc>
	<svc><!-- MDR Thüringen HD - Satellit --><TSID>425</TSID><SID>2872</SID><ONID>1</ONID><svcNum>46</svcNum></svc>
	<svc><!-- MDR Thüringen HD - Kabel BW --><TSID>023B</TSID><SID>DF11</SID><ONID>270F</ONID><svcNum>46</svcNum></svc>
	<svc><!-- MDR Thüringen HD - Kabeldeutschland --><TSID>431</TSID><SID>2872</SID><ONID>1</ONID><svcNum>46</svcNum></svc>
	<svc><!-- SR Fernsehen HD - Satellit --><TSID>40F</TSID><SID>288A</SID><ONID>1</ONID><svcNum>47</svcNum></svc>
	<svc><!-- SR Fernsehen HD - Kabel BW --><TSID>023B</TSID><SID>DF10</SID><ONID>270F</ONID><svcNum>47</svcNum></svc>
	<svc><!-- SR Fernsehen - Kabeldeutschland --><TSID>41B</TSID><SID>6F46</SID><ONID>1</ONID><svcNum>47</svcNum></svc>
	<svc><!-- SR Fernsehen HD - Kabeldeutschland --><TSID>431</TSID><SID>288A</SID><ONID>1</ONID><svcNum>47</svcNum></svc>
	<svc><!-- NDR FS MV HD - Satellit --><TSID>401</TSID><SID>2858</SID><ONID>1</ONID><svcNum>48</svcNum></svc>
	<svc><!-- NDR FS MV - Kabel BW --><TSID>431</TSID><SID>6E40</SID><ONID>A401</ONID><svcNum>48</svcNum></svc>
	<svc><!-- NDR FS MV HD - Kabeldeutschland --><TSID>431</TSID><SID>2858</SID><ONID>1</ONID><svcNum>48</svcNum></svc>
	<svc><!-- N24 DOKU - Satellit --><TSID>5</TSID><SID>30</SID><ONID>85</ONID><svcNum>49</svcNum></svc>
	<svc><!-- N24 DOKU - Kabeldeutschland --><TSID>2725</TSID><SID>C75D</SID><ONID>F001</ONID><svcNum>49</svcNum></svc>
	<svc><!-- TOGGO plus - Satellit --><TSID>441</TSID><SID>2EFE</SID><ONID>1</ONID><svcNum>50</svcNum></svc>
	<svc><!-- TOGGO plus - Kabeldeutschland --><TSID>2712</TSID><SID>D04E</SID><ONID>F001</ONID><svcNum>50</svcNum></svc>
	<svc><!-- NDR FS SH HD - Satellit --><TSID>401</TSID><SID>285A</SID><ONID>1</ONID><svcNum>51</svcNum></svc>
	<svc><!-- NDR FS SH - Kabel BW --><TSID>431</TSID><SID>6E43</SID><ONID>A401</ONID><svcNum>51</svcNum></svc>
	<svc><!-- NDR FS SH HD - Kabeldeutschland --><TSID>431</TSID><SID>285A</SID><ONID>1</ONID><svcNum>51</svcNum></svc>
	<svc><!-- Sky Sport News HD - Satellit --><TSID>C</TSID><SID>6C</SID><ONID>85</ONID><svcNum>52</svcNum></svc>
	<svc><!-- ARD-alpha - Satellit --><TSID>445</TSID><SID>6F47</SID><ONID>1</ONID><svcNum>53</svcNum></svc>
	<svc><!-- ARD-alpha - Kabel BW --><TSID>41B</TSID><SID>6F47</SID><ONID>A401</ONID><svcNum>53</svcNum></svc>
	<svc><!-- ARD-alpha - Kabeldeutschland --><TSID>41B</TSID><SID>6F47</SID><ONID>1</ONID><svcNum>53</svcNum></svc>
	<svc><!-- Zee One HD - Satellit --><TSID>409</TSID><SID>2775</SID><ONID>1</ONID><svcNum>54</svcNum></svc>
	<svc><!-- Zee One - Kabel BW --><TSID>d3</TSID><SID>4e9d</SID><ONID>270F</ONID><svcNum>54</svcNum></svc>
	<svc><!-- Zee One - Kabeldeutschland --><TSID>2721</TSID><SID>CF6F</SID><ONID>F001</ONID><svcNum>54</svcNum></svc>
	<svc><!-- Bibel TV HD - Satellit --><TSID>3EB</TSID><SID>33A8</SID><ONID>1</ONID><svcNum>55</svcNum></svc>
	<svc><!-- Bibel TV HD - Kabel BW --><TSID>79</TSID><SID>C79F</SID><ONID>270F</ONID><svcNum>55</svcNum></svc>
	<svc><!-- Bibel TV HD - Kabeldeutschland --><TSID>271B</TSID><SID>C387</SID><ONID>F001</ONID><svcNum>55</svcNum></svc>
	<svc><!-- Welt der Wunder - Satellit --><TSID>45B</TSID><SID>332F</SID><ONID>1</ONID><svcNum>56</svcNum></svc>
	<svc><!-- Welt der Wunder - Kabeldeutschland --><TSID>2725</TSID><SID>C763</SID><ONID>F001</ONID><svcNum>56</svcNum></svc>
	<svc><!-- eoTV - Satellit --><TSID>F</TSID><SID>27</SID><ONID>85</ONID><svcNum>57</svcNum></svc>
	<svc><!-- eoTV - Kabel BW --><TSID>BF</TSID><SID>4AAD</SID><ONID>270F</ONID><svcNum>57</svcNum></svc>
	<svc><!-- eoTV - Kabeldeutschland --><TSID>2717</TSID><SID>D052</SID><ONID>F001</ONID><svcNum>57</svcNum></svc>
	<svc><!-- Juwelo HD - Satellit --><TSID>455</TSID><SID>151B</SID><ONID>1</ONID><svcNum>58</svcNum></svc>
	<svc><!-- Juwelo HD - Kabel BW --><TSID>1C3</TSID><SID>B02F</SID><ONID>270F</ONID><svcNum>58</svcNum></svc>
	<svc><!-- Juwelo TV - Kabeldeutschland --><TSID>2715</TSID><SID>D173</SID><ONID>F001</ONID><svcNum>58</svcNum></svc>
	<svc><!-- Sky 1 HD - Satellit --><TSID>2</TSID><SID>93</SID><ONID>85</ONID><svcNum>59</svcNum></svc>
	<svc><!-- Sky 1 HD - Kabel BW --><TSID>D</TSID><SID>93</SID><ONID>85</ONID><svcNum>59</svcNum></svc>
	</favoritesGermany>
	<favoritesAustria>
		<svc><!-- ORF1 HD - Austria Sat --><TSID>3EF</TSID><SID>132F</SID><ONID>1</ONID><svcNum>1</svcNum></svc>
		<svc><!-- ORF2W HD - Austria Sat --><TSID>3EF</TSID><SID>1330</SID><ONID>1</ONID><svcNum>2</svcNum></svc>
		<svc><!-- ATV HD - Austria Sat --><TSID>3EB</TSID><SID>33AC</SID><ONID>1</ONID><svcNum>3</svcNum></svc>
		<svc><!-- PULS 4 Austria - Austria Sat --><TSID>43A</TSID><SID>4E27</SID><ONID>1</ONID><svcNum>4</svcNum></svc>
		<svc><!-- SAT.1 A - Austria Sat --><TSID>43A</TSID><SID>4E25</SID><ONID>1</ONID><svcNum>5</svcNum></svc>
		<svc><!-- RTL Austria - Austria Sat --><TSID>443</TSID><SID>7080</SID><ONID>1</ONID><svcNum>6</svcNum></svc>
		<svc><!-- ProSieben Austria - Austria Sat --><TSID>43A</TSID><SID>4E22</SID><ONID>1</ONID><svcNum>7</svcNum></svc>
		<svc><!-- VOX Austria - Austria Sat --><TSID>443</TSID><SID>7085</SID><ONID>1</ONID><svcNum>8</svcNum></svc>
		<svc><!-- zdf_neo HD - Satellit --><TSID>3F3</TSID><SID>2B7A</SID><ONID>1</ONID><svcNum>9</svcNum></svc>
		<svc><!-- WDR HD Köln - Satellit --><TSID>4B1</TSID><SID>6EA5</SID><ONID>1</ONID><svcNum>10</svcNum></svc>
		<svc><!-- BR Fernsehen Süd HD - Satellit --><TSID>401</TSID><SID>2855</SID><ONID>1</ONID><svcNum>11</svcNum></svc>
		<svc><!-- SUPER RTL A - Austria Sat --><TSID>443</TSID><SID>708F</SID><ONID>1</ONID><svcNum>12</svcNum></svc>
		<svc><!-- ATV2 - Austria Sat --><TSID>3EB</TSID><SID>33A7</SID><ONID>1</ONID><svcNum>13</svcNum></svc>
		<svc><!-- ServusTV HD Oesterreich - Austria Sat --><TSID>3EF</TSID><SID>1331</SID><ONID>1</ONID><svcNum>14</svcNum></svc>
		<svc><!-- Pro7 MAXX Austria - Austria Sat --><TSID>407</TSID><SID>14BF</SID><ONID>1</ONID><svcNum>15</svcNum></svc>
		<svc><!-- 3sat HD - Satellit --><TSID>3F2</TSID><SID>2B8E</SID><ONID>1</ONID><svcNum>16</svcNum></svc>
		<svc><!-- MDR S-Anhalt HD - Satellit --><TSID>425</TSID><SID>2871</SID><ONID>1</ONID><svcNum>17</svcNum></svc>
		<svc><!-- ZDFinfo HD - Satellit --><TSID>3F2</TSID><SID>2BA2</SID><ONID>1</ONID><svcNum>18</svcNum></svc>
		<svc><!-- DMAX Austria - Austria Sat --><TSID>7</TSID><SID>49</SID><ONID>85</ONID><svcNum>19</svcNum></svc>
		<svc><!-- arte HD - Satellit --><TSID>3FB</TSID><SID>283E</SID><ONID>1</ONID><svcNum>20</svcNum></svc>
		<svc><!-- Das Erste HD - Austria Sat --><TSID>3FB</TSID><SID>283D</SID><ONID>1</ONID><svcNum>21</svcNum></svc>
		<svc><!-- ZDF HD - Austria Sat --><TSID>3F3</TSID><SID>2B66</SID><ONID>1</ONID><svcNum>22</svcNum></svc>
		<svc><!-- KiKA HD - Austria Sat --><TSID>3F2</TSID><SID>2B98</SID><ONID>1</ONID><svcNum>23</svcNum></svc>
		<svc><!-- ORF III HD - Austria Sat --><TSID>3ED</TSID><SID>33FC</SID><ONID>1</ONID><svcNum>24</svcNum></svc>
		<svc><!-- 3sat HD - Austria Sat --><TSID>3F2</TSID><SID>2B8E</SID><ONID>1</ONID><svcNum>25</svcNum></svc>
		<svc><!-- SPORT1 - Austria Sat --><TSID>21</TSID><SID>384</SID><ONID>85</ONID><svcNum>26</svcNum></svc>
		<svc><!-- Eurosport 1 Deutschland - Austria Sat --><TSID>443</TSID><SID>79E0</SID><ONID>1</ONID><svcNum>27</svcNum></svc>
		<svc><!-- ORF SPORT+ HD - Austria Sat --><TSID>3ED</TSID><SID>33FD</SID><ONID>1</ONID><svcNum>28</svcNum></svc>
		<svc><!-- oe24.TV HD - Austria Sat --><TSID>3ED</TSID><SID>3402</SID><ONID>1</ONID><svcNum>29</svcNum></svc>
		<svc><!-- Schau TV HD - Austria Sat --><TSID>3EB</TSID><SID>33A9</SID><ONID>1</ONID><svcNum>30</svcNum></svc>
		<svc><!-- TELE 5 - Satellit --><TSID>21</TSID><SID>33</SID><ONID>85</ONID><svcNum>31</svcNum></svc>
		<svc><!-- SIXX - Satellit --><TSID>5</TSID><SID>308</SID><ONID>85</ONID><svcNum>32</svcNum></svc>
		<svc><!-- Pro7 MAXX - Satellit --><TSID>453</TSID><SID>4461</SID><ONID>1</ONID><svcNum>33</svcNum></svc>
		<svc><!-- SWR RP HD - Satellit --><TSID>3FB</TSID><SID>2840</SID><ONID>1</ONID><svcNum>34</svcNum></svc>
		<svc><!-- ONE HD - Satellit --><TSID>40F</TSID><SID>2888</SID><ONID>1</ONID><svcNum>35</svcNum></svc>
		<svc><!-- Eurosport 1 Deutschland - Satellit --><TSID>443</TSID><SID>79E0</SID><ONID>1</ONID><svcNum>36</svcNum></svc>
		<svc><!-- MDR Sachsen HD - Satellit --><TSID>425</TSID><SID>2870</SID><ONID>1</ONID><svcNum>37</svcNum></svc>
		<svc><!-- TELE 5 - Austria Sat --><TSID>21</TSID><SID>33</SID><ONID>85</ONID><svcNum>38</svcNum></svc>
		<svc><!-- Disney Channel - Austria Sat --><TSID>5</TSID><SID>701</SID><ONID>85</ONID><svcNum>39</svcNum></svc>
		<svc><!-- tagesschau24 HD - Satellit --><TSID>40F</TSID><SID>2887</SID><ONID>1</ONID><svcNum>40</svcNum></svc>
		<svc><!-- ServusTV HD Deutschland - Satellit --><TSID>3EF</TSID><SID>1332</SID><ONID>1</ONID><svcNum>41</svcNum></svc>
		<svc><!-- RTLplus Austria - Austria Sat --><TSID>3EB</TSID><SID>33AD</SID><ONID>1</ONID><svcNum>42</svcNum></svc>
		<svc><!-- arte HD - Austria Sat --><TSID>3FB</TSID><SID>283E</SID><ONID>1</ONID><svcNum>43</svcNum></svc>
		<svc><!-- tagesschau24 HD - Austria Sat --><TSID>40F</TSID><SID>2887</SID><ONID>1</ONID><svcNum>44</svcNum></svc>
		<svc><!-- ONE HD - Austria Sat --><TSID>40F</TSID><SID>2888</SID><ONID>1</ONID><svcNum>45</svcNum></svc>
		<svc><!-- MDR Thüringen HD - Satellit --><TSID>425</TSID><SID>2872</SID><ONID>1</ONID><svcNum>46</svcNum></svc>
		<svc><!-- PHOENIX HD - Austria Sat --><TSID>401</TSID><SID>285B</SID><ONID>1</ONID><svcNum>47</svcNum></svc>
		<svc><!-- NDR FS MV HD - Satellit --><TSID>401</TSID><SID>2858</SID><ONID>1</ONID><svcNum>48</svcNum></svc>
		<svc><!-- zdf_neo HD - Austria Sat --><TSID>3F3</TSID><SID>2B7A</SID><ONID>1</ONID><svcNum>49</svcNum></svc>
		<svc><!-- ZDFinfo HD - Austria Sat --><TSID>3F2</TSID><SID>2BA2</SID><ONID>1</ONID><svcNum>50</svcNum></svc>
		<svc><!-- NDR FS SH HD - Satellit --><TSID>401</TSID><SID>285A</SID><ONID>1</ONID><svcNum>51</svcNum></svc>
		<svc><!-- Sky Sport News HD - Satellit --><TSID>C</TSID><SID>6C</SID><ONID>85</ONID><svcNum>52</svcNum></svc>
		<svc><!-- R9 Oesterreich HD - Austria Sat --><TSID>3ED</TSID><SID>3400</SID><ONID>1</ONID><svcNum>53</svcNum></svc>
		<svc><!-- Zee One HD - Satellit --><TSID>409</TSID><SID>2775</SID><ONID>1</ONID><svcNum>54</svcNum></svc>
		<svc><!-- Bibel TV HD - Satellit --><TSID>3EB</TSID><SID>33A8</SID><ONID>1</ONID><svcNum>55</svcNum></svc>
		<svc><!-- NDR FS HH HD - Austria Sat --><TSID>401</TSID><SID>2859</SID><ONID>1</ONID><svcNum>56</svcNum></svc>
		<svc><!-- WDR HD Köln - Austria Sat --><TSID>4B1</TSID><SID>6EA5</SID><ONID>1</ONID><svcNum>57</svcNum></svc>
		<svc><!-- MDR Thüringen HD - Austria Sat --><TSID>425</TSID><SID>2872</SID><ONID>1</ONID><svcNum>58</svcNum></svc>
		<svc><!-- BR Fernsehen Süd HD - Austria Sat --><TSID>401</TSID><SID>2855</SID><ONID>1</ONID><svcNum>59</svcNum></svc>
		<svc><!-- SWR BW HD - Austria Sat --><TSID>3FB</TSID><SID>283F</SID><ONID>1</ONID><svcNum>60</svcNum></svc>
		<svc><!-- hr-fernsehen HD - Austria Sat --><TSID>425</TSID><SID>2873</SID><ONID>1</ONID><svcNum>61</svcNum></svc>
		<svc><!-- rbb Berlin HD - Austria Sat --><TSID>425</TSID><SID>286F</SID><ONID>1</ONID><svcNum>62</svcNum></svc>
		<svc><!-- SR Fernsehen HD - Austria Sat --><TSID>40F</TSID><SID>288A</SID><ONID>1</ONID><svcNum>63</svcNum></svc>
		<svc><!-- PULS 4 HD Austria - Austria Sat --><TSID>407</TSID><SID>14B7</SID><ONID>1</ONID><svcNum>72</svcNum></svc>
		<svc><!-- SAT.1 HD Austria - Austria Sat --><TSID>407</TSID><SID>14B4</SID><ONID>1</ONID><svcNum>73</svcNum></svc>
		<svc><!-- RTL HD Austria - Austria Sat --><TSID>411</TSID><SID>2E87</SID><ONID>1</ONID><svcNum>74</svcNum></svc>
		<svc><!-- ProSieben HD Austria - Austria Sat --><TSID>407</TSID><SID>14B5</SID><ONID>1</ONID><svcNum>75</svcNum></svc>
		<svc><!-- VOX HD Austria - Austria Sat --><TSID>411</TSID><SID>2E91</SID><ONID>1</ONID><svcNum>76</svcNum></svc>
		<svc><!-- kabel eins HD Austria - Austria Sat --><TSID>3F9</TSID><SID>EF8A</SID><ONID>1</ONID><svcNum>77</svcNum></svc>
		<svc><!-- RTL II HD Austria - Austria Sat --><TSID>411</TSID><SID>2EA5</SID><ONID>1</ONID><svcNum>78</svcNum></svc>
		<svc><!-- WELT HD - Austria Sat --><TSID>41D</TSID><SID>527E</SID><ONID>1</ONID><svcNum>79</svcNum></svc>
		<svc><!-- NICKELODEON HD - Austria Sat --><TSID>41D</TSID><SID>5273</SID><ONID>1</ONID><svcNum>80</svcNum></svc>
		<svc><!-- TELE 5 HD Austria - Austria Sat --><TSID>455</TSID><SID>152D</SID><ONID>1</ONID><svcNum>81</svcNum></svc>
		<svc><!-- Deluxe Music HD Austria - Austria Sat --><TSID>41F</TSID><SID>1589</SID><ONID>1</ONID><svcNum>82</svcNum></svc>